spring:
  datasource:
    url: jdbc:h2:mem:agaat_pnae_memory_db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: 123456
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      "[hibernate.generate_statistics]": false
    defer-datasource-initialization: true