server:
  tomcat:
    threads:
      max: 40

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:agaat_pnae_memory_db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: CatalogoServiceHikariCP
  jpa:
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL}
    hibernate:
      ddl-auto: create # TODO to none
    properties:
      "[hibernate.generate_statistics]": ${JPA_GENERATE_STATISTICS}
      "[hibernate.connection.provider_disables_autocommit]": true
  h2:
    console:
      enabled: true
      path: /h2